version: '3.8'

services:
  # Investor Agent MCP Bridge Service
  investor-agent-bridge:
    build:
      context: .
      dockerfile: Dockerfile.bridge
    container_name: investor-agent-bridge
    ports:
      - "8000:8000"
    environment:
      - ALPACA_API_KEY=${ALPACA_API_KEY}
      - ALPACA_API_SECRET=${ALPACA_API_SECRET}
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - investor-agent-network

  # n8n Workflow Automation
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD:-admin}
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=${TIMEZONE:-America/New_York}
      # AI/LLM API Keys (optional - configure based on your LLM provider)
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      # Bridge service URL for n8n to access
      - INVESTOR_AGENT_BRIDGE_URL=http://investor-agent-bridge:8000
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n/workflows:/home/node/.n8n/workflows:rw
    restart: unless-stopped
    depends_on:
      investor-agent-bridge:
        condition: service_healthy
    networks:
      - investor-agent-network

volumes:
  n8n_data:
    driver: local

networks:
  investor-agent-network:
    driver: bridge
